name: Auto-merge PRs when labeled

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Run auto-merge script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOLABEL_NAME: bug      # label name to watch for
          MERGE_METHOD: merge                # merge, squash or rebase
          POLL_INTERVAL_SECONDS: "10"         # poll frequency
          POLL_TIMEOUT_SECONDS: "900"         # how long to wait for checks (default 15 mins)
        run: node .github/scripts/auto-merge.js
